/**
*	@file EnemyTex.h
*	@author 中地
*			中本
*	@brief キャラクターの画像リスト
*/


#ifndef ENEMYTEX_H_
#define ENEMYTEX_H_

#include "GameSceneTex.h"

enum EnemyCategoryTextureList
{
	// オハギ
	OHAGI_SPAWN_TEX,
	OHAGI_FAR_TEX,
	OHAGI_NEAR_TEX,	
	OHAGI_PLAYER_TEX,
	OHAGI_KILLANIME_TEX,

	// ウメ
	UME_SPAWN_TEX,
	UME_WALK_TEX,
	UME_LOOK_TEX,
	UME_PLAYER_TEX,
	UME_KILLANIME_TEX,

	// サクラ
	SAKURA_SPAWN_TEX,
	SAKURA_WALK_TEX,
	SAKURA_LOOK_TEX,
	SAKURA_PLAYER_TEX,
	SAKURA_KILLANIME_TEX,

	// オラン
	ORAN_SPAWN_TEX,
	ORAN_FAR_TEX,
	ORAN_NEAR_TEX,
	ORAN_PLAYER_TEX,
	ORAN_KILLANIME_TEX,

	// ボタン
	BOTAN_PLAYER_TEX,
	BOTAN_KILLANIME_TEX,

	// マーガレット
	MARGARET_SPAWN_BASE_TEX,
	MARGARET_SPAWN_EYE_TEX,
	MARGARET_KILLANIME_TEX,
	// マーガレットの目のUI
	MARGARET_EYE_TEX,
	MARGARET_PIZA_1,
	MARGARET_PIZA_2,
	MARGARET_PIZA_3,
	MARGARET_PIZA_4,
	MARGARET_PIZA_5,
	MARGARET_PIZA_6,
	MARGARET_PIZA_7,
	MARGARET_PIZA_8,
	MARGARET_PIZA_9,

	// エネミー最大
	ENEMY_TEXTURE_MAX,
};

#define TEXTURE_CATEGORY_ENEMY (SceneId::EnemyScene)				//!< ゲーム本編カテゴリー

#endif