#ifndef GAME_OBJECTTEX_H_
#define GAME_OBJECTTEX_H_

#include "GameSceneTex.h"

enum GameObjectCategoryTextureList {

	// GAME_SCENE_OBJECT
	OBJECT_MASK_TEX,				//!< ”wŒi

	OBJECT_MASK_UI_TEX,

	OBJECT_CONTROL_UI_TEX,
	OBJECT_ONHIT_CONTROL_UI_TEX,

	OBJECT_DESCRIPTION_UI_TEX,

	OBJECT_CANDLE_BIG_TEX,
	OBJECT_CANDLE_SMALL_TEX,

	OBJECT_CANDLE_STAND_CENTER_TEX,
	OBJECT_CANDLE_STAND_SIDE_TEX,

	OBJECT_CANDLE_CENTER_EFFECT_TEX,
	OBJECT_CANDLE_LEFT_EFFECT_TEX,
	OBJECT_CANDLE_RIGHT_EFFECT_TEX,

	OBJECT_FIRE_TEX,
	OBJECT_FIRE_BIG_TEX,
	OBJECT_FIRE_SMALL_TEX,

	OBJECT_CRYSTAL_TEX,
	OBJECT_ONHIT_CRYSTAL_TEX,

	OBJECT_WATCH_TEX,
	OBJECT_ONHITWATCH_TEX,

	OBJECT_MAIN_UI_TEX,

	// MONITOR_SCENE
	OBJECT_MONITOR_BUTTOM1_TEX,
	OBJECT_MONITOR_BUTTOM2_TEX,
	OBJECT_MONITOR_BUTTOM3_TEX,
	OBJECT_MONITOR_BUTTOM4_TEX,
	OBJECT_MONITOR_BUTTOM5_TEX,
	OBJECT_MONITOR_BUTTOM6_TEX,

	OBJECT_MONITOR_ONBUTTOM1_TEX,
	OBJECT_MONITOR_ONBUTTOM2_TEX,
	OBJECT_MONITOR_ONBUTTOM3_TEX,
	OBJECT_MONITOR_ONBUTTOM4_TEX,
	OBJECT_MONITOR_ONBUTTOM5_TEX,
	OBJECT_MONITOR_ONBUTTOM6_TEX,

	OBJECT_MONITOR_MAP_TEX,
	OBJECT_MONITOR_PLAYER_TEX,

	GAME_OBJECT_TEXTURE_MAX,			//!< ƒŠƒXƒgÅ‘å”
};

#define TEXTURE_CATEGORY_GAME_OBJECT (SceneId::GameObjectScene)				//!< ƒQ[ƒ€–{•ÒƒJƒeƒSƒŠ[

#endif